### ISSUE TITLE
Unable to load some downloaded files

### ISSUE THREAD

**Issue by SeitaroShinagawa** [emansim/text2image#4]
I tried to run your code for MS COCO by "python alignDraw.py models/coco-captions-32x32.json", but I'm faced with a file loading problem.  

Then, I tried to check whether additional downloaded files are possible to load or not. 

I can't to load these files as below,
*train-images-56x56.npy, train-captions.npy, train-captions-len.npy,
train-cap2im.pkl, dev-images-32x32.npy, dev-images-56x56.npy, dev-captions.npy,
dev-captions-len.npy, dev-cap2im.pkl, gan.hdf5*

I suspected that I had some mistakes, firstly. However, I can load these files as below,
*train-images-32x32.npy,
test-images-32x32.npy, test-captions.npy, test-captions-len.npy, test-cap2im.pkl,
dictionary.pkl*

I'm not sure why the difference happens. 
I added all error log in the end of this issue.

**my environment**
- pyenv anaconda2-2.4.1
- Python(2.7.11)
- numpy(1.10.4)
- scipy(0.17.0)
- Theano(0.7.0)
- h5py(2.5.0)

Thanks !
```python
import numpy as np
import pickle

>>> data=np.load("train-images-56x56.npy")
Traceback (most recent call last):
 File "<stdin>", line 1, in <module>
 File "/home/is/seitaro-s/.pyenv/versions/anaconda2-2.4.1/envs/semantic-embedding-anaconda2/lib/python2.7/site-packages/numpy/lib/npyio.py", line 406, in load
   pickle_kwargs=pickle_kwargs)
 File "/home/is/seitaro-s/.pyenv/versions/anaconda2-2.4.1/envs/semantic-embedding-anaconda2/lib/python2.7/site-packages/numpy/lib/format.py", line 673, in read_array
   array.shape = shape
ValueError: total size of new array must be unchanged

>>> data=np.load("train-captions.npy")
Traceback (most recent call last):
 File "<stdin>", line 1, in <module>
 File "/home/is/seitaro-s/.pyenv/versions/anaconda2-2.4.1/envs/semantic-embedding-anaconda2/lib/python2.7/site-packages/numpy/lib/npyio.py", line 416, in load
   "Failed to interpret file %s as a pickle" % repr(file))
IOError: Failed to interpret file 'train-captions.npy' as a pickle

>>> data=np.load("train-captions-len.npy")
Traceback (most recent call last):
 File "<stdin>", line 1, in <module>
 File "/home/is/seitaro-s/.pyenv/versions/anaconda2-2.4.1/envs/semantic-embedding-anaconda2/lib/python2.7/site-packages/numpy/lib/npyio.py", line 406, in load
   pickle_kwargs=pickle_kwargs)
 File "/home/is/seitaro-s/.pyenv/versions/anaconda2-2.4.1/envs/semantic-embedding-anaconda2/lib/python2.7/site-packages/numpy/lib/format.py", line 673, in read_array
   array.shape = shape
ValueError: total size of new array must be unchanged

>>> data=np.load("dev-images-32x32.npy")
Traceback (most recent call last):
 File "<stdin>", line 1, in <module>
 File "/home/is/seitaro-s/.pyenv/versions/anaconda2-2.4.1/envs/semantic-embedding-anaconda2/lib/python2.7/site-packages/numpy/lib/npyio.py", line 392, in load
   fid.seek(-N, 1)  # back-up
IOError: [Errno 22] Invalid argument

>>> data=np.load("dev-images-56x56.npy")
Traceback (most recent call last):
 File "<stdin>", line 1, in <module>
 File "/home/is/seitaro-s/.pyenv/versions/anaconda2-2.4.1/envs/semantic-embedding-anaconda2/lib/python2.7/site-packages/numpy/lib/npyio.py", line 406, in load
   pickle_kwargs=pickle_kwargs)
 File "/home/is/seitaro-s/.pyenv/versions/anaconda2-2.4.1/envs/semantic-embedding-anaconda2/lib/python2.7/site-packages/numpy/lib/format.py", line 673, in read_array
   array.shape = shape
ValueError: total size of new array must be unchanged

>>> data=np.load("dev-captions.npy")
Traceback (most recent call last):
 File "<stdin>", line 1, in <module>
 File "/home/is/seitaro-s/.pyenv/versions/anaconda2-2.4.1/envs/semantic-embedding-anaconda2/lib/python2.7/site-packages/numpy/lib/npyio.py", line 392, in load
   fid.seek(-N, 1)  # back-up
IOError: [Errno 22] Invalid argument

>>> data=np.load("dev-captions-len.npy")
Traceback (most recent call last):
 File "<stdin>", line 1, in <module>
 File "/home/is/seitaro-s/.pyenv/versions/anaconda2-2.4.1/envs/semantic-embedding-anaconda2/lib/python2.7/site-packages/numpy/lib/npyio.py", line 392, in load
   fid.seek(-N, 1)  # back-up
IOError: [Errno 22] Invalid argument

>>> with open('train-cap2im.pkl','r') as f:
...     data = pickle.load(f)
... 
Traceback (most recent call last):
 File "<stdin>", line 2, in <module>
 File "/home/is/seitaro-s/.pyenv/versions/anaconda2-2.4.1/envs/semantic-embedding-anaconda2/lib/python2.7/pickle.py", line 1384, in load
   return Unpickler(file).load()
 File "/home/is/seitaro-s/.pyenv/versions/anaconda2-2.4.1/envs/semantic-embedding-anaconda2/lib/python2.7/pickle.py", line 864, in load
   dispatch[key](self)
 File "/home/is/seitaro-s/.pyenv/versions/anaconda2-2.4.1/envs/semantic-embedding-anaconda2/lib/python2.7/pickle.py", line 886, in load_eof
   raise EOFError
EOFError

>>> with open('dev-cap2im.pkl','r') as f:
...     data = pickle.load(f)
... 
Traceback (most recent call last):
 File "<stdin>", line 2, in <module>
 File "/home/is/seitaro-s/.pyenv/versions/anaconda2-2.4.1/envs/semantic-embedding-anaconda2/lib/python2.7/pickle.py", line 1384, in load
   return Unpickler(file).load()
 File "/home/is/seitaro-s/.pyenv/versions/anaconda2-2.4.1/envs/semantic-embedding-anaconda2/lib/python2.7/pickle.py", line 864, in load
   dispatch[key](self)
 File "/home/is/seitaro-s/.pyenv/versions/anaconda2-2.4.1/envs/semantic-embedding-anaconda2/lib/python2.7/pickle.py", line 886, in load_eof
   raise EOFError
EOFError

>>> with h5py.File('gan.hdf5','r') as hdf5:
...     print hdf5['skipthought2image']
... 
Traceback (most recent call last):
 File "<stdin>", line 2, in <module>
 File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/tmp/pip-build-BQojpm/h5py/h5py/_objects.c:2405)
 File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/tmp/pip-build-BQojpm/h5py/h5py/_objects.c:2362)
 File "/home/is/seitaro-s/.local/lib/python2.7/site-packages/h5py/_hl/group.py", line 164, in __getitem__
   oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
 File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/tmp/pip-build-BQojpm/h5py/h5py/_objects.c:2405)
 File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/tmp/pip-build-BQojpm/h5py/h5py/_objects.c:2362)
 File "h5py/h5o.pyx", line 190, in h5py.h5o.open (/tmp/pip-build-BQojpm/h5py/h5py/h5o.c:3317)
KeyError: "Unable to open object (Object 'skipthought2image' doesn't exist)"

**Comment by emansim** [comment]
Hi @SeitaroShinagawa 

Firstly, before running alignDraw make sure to set correct path of data in coco-captions-32x32.json file.

I am not quite sure why are you getting these errors. I tried downloading and loading those files in several different workstations and I never encountered those errors. Plus the errors you are getting are inconsistent.

**Comment by SeitaroShinagawa** [comment]
Hi @emansim 

Thanks for replying to me so quickly! Now, my trouble has been solved.

As you said, these errors are really inconsistent. Then I downloaded files again and they have no problems with loading. 
I guess there were something wrong with my first download.
